const countryList = {
    AED: "United Arab Emirates",
    AFN: "Afghanistan",
    XCD: "Antigua and Barbuda",
    ALL: "Albania",
    AMD: "Armenia",
    ANG: "Netherlands Antilles",
    AOA: "Angola",
    ARS: "Argentina",
    AUD: "Australia",
    AZN: "Azerbaijan",
    BAM: "Bosnia and Herzegovina",
    BBD: "Barbados",
    BDT: "Bangladesh",
    XOF: "West African Economic and Monetary Union",
    BGN: "Bulgaria",
    BHD: "Bahrain",
    BIF: "Burundi",
    BMD: "Bermuda",
    BND: "Brunei",
    BOB: "Bolivia",
    BRL: "Brazil",
    BSD: "Bahamas",
    CVE: "Cape Verde",
    CAD: "Canada",
    CDF: "Democratic Republic of the Congo",
    XAF: "Central African Republic",
    CHF: "Switzerland",
    CLP: "Chile",
    CNY: "China",
    COP: "Colombia",
    CRC: "Costa Rica",
    CZK: "Czech Republic",
    DJF: "Djibouti",
    DKK: "Denmark",
    DOP: "Dominican Republic",
    DZD: "Algeria",
    EGP: "Egypt",
    ETB: "Ethiopia",
    EUR: "France",
    FJD: "Fiji",
    FKP: "Falkland Islands",
    GBP: "United Kingdom",
    GEL: "Georgia",
    GGP: "Guernsey",
    GHS: "Ghana",
    GIP: "Gibraltar",
    GMD: "Gambia",
    GNF: "Guinea",
    GTQ: "Guatemala",
    GYD: "Guyana",
    HKD: "Hong Kong",
    HNL: "Honduras",
    HRK: "Croatia",
    HTG: "Haiti",
    HUF: "Hungary",
    IDR: "Indonesia",
    ILS: "Israel",
    INR: "India",
    IQD: "Iraq",
    IRR: "Iran",
    ISK: "Iceland",
    JMD: "Jamaica",
    JOD: "Jordan",
    JPY: "Japan",
    KES: "Kenya",
    KGS: "Kyrgyzstan",
    KHR: "Cambodia",
    KMF: "Comoros",
    KPW: "North Korea",
    KRW: "South Korea",
    KWD: "Kuwait",
    KYD: "Cayman Islands",
    KZT: "Kazakhstan",
    LAK: "Laos",
    LBP: "Lebanon",
    LKR: "Sri Lanka",
    LRD: "Liberia",
    LSL: "Lesotho",
    LTL: "Lithuania",
    LVL: "Latvia",
    LYD: "Libya",
    MAD: "Morocco",
    MDL: "Moldova",
    MGA: "Madagascar",
    MKD: "North Macedonia",
    MMK: "Myanmar",
    MNT: "Mongolia",
    MOP: "Macau",
    MUR: "Mauritius",
    MVR: "Maldives",
    MWK: "Malawi",
    MXN: "Mexico",
    MYR: "Malaysia",
    MZN: "Mozambique",
    NAD: "Namibia",
    NGN: "Nigeria",
    NPR: "Nepal",
    NZD: "New Zealand",
    OMR: "Oman",
    PAB: "Panama",
    PEN: "Peru",
    PGK: "Papua New Guinea",
    PHP: "Philippines",
    PKR: "Pakistan",
    PLN: "Poland",
    PYG: "Paraguay",
    QAR: "Qatar",
    RON: "Romania",
    RSD: "Serbia",
    RUB: "Russia",
    RWF: "Rwanda",
    SAR: "Saudi Arabia",
    SBD: "Solomon Islands",
    SCR: "Seychelles",
    SDG: "Sudan",
    SEK: "Sweden",
    SGD: "Singapore",
    SKK: "Slovakia",
    SLL: "Sierra Leone",
    SOS: "Somalia",
    SRD: "Suriname",
    STD: "São Tomé and Príncipe",
    SVC: "El Salvador",
    SYP: "Syria",
    SZL: "Eswatini",
    THB: "Thailand",
    TJS: "Tajikistan",
    TMT: "Turkmenistan",
    TND: "Tunisia",
    TOP: "Tonga",
    TRY: "Turkey",
    TTD: "Trinidad and Tobago",
    TWD: "Taiwan",
    TZS: "Tanzania",
    UAH: "Ukraine",
    UGX: "Uganda",
    USD: "United States",
    UYU: "Uruguay",
    UZS: "Uzbekistan",
    VEF: "Venezuela",
    VND: "Vietnam",
    VUV: "Vanuatu",
    YER: "Yemen",
    ZAR: "South Africa",
    ZMK: "Zambia",
    ZWD: "Zimbabwe"
  };

export default countryList;
